// Proposes an upstream GeoGebra merge for review (Linear OLM-2025), like the Ketcher fork's sync:
// merges geogebra/geogebra main into the Robotutor branch on a proposal branch, preserving both
// histories. It never force-pushes, merges the PR or publishes a release; conflicts stop it with
// the conflicting paths. Runs in a temporary worktree, so the caller's checkout is untouched.
//
//   node robotutor/sync.mjs                 merge locally and report (dry run)
//   node robotutor/sync.mjs --check         also build the bundle and run the contract (check.sh)
//   node robotutor/sync.mjs --push [--check] push the proposal branch and open or update its PR
import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

export const REPOSITORY = "Weller-Precision-Industries/geogebra";
export const BASE = "robotutor";
export const HEAD = "automation/geogebra-upstream-sync";
export const UPSTREAM = { repository: "geogebra/geogebra", branch: "main" };
const UPSTREAM_URL = `https://github.com/${UPSTREAM.repository}.git`;
const UPSTREAM_REF = "refs/remotes/robotutor-upstream/main";

export function checkedSha(value) {
	if (!/^[a-f0-9]{40}$/.test(value)) throw new Error("Expected an exact 40-character commit SHA");
	return value;
}

export function run(program, args, options = {}) {
	return execFileSync(program, args, {
		encoding: "utf8",
		timeout: 30 * 60_000,
		maxBuffer: 64 * 1024 * 1024,
		stdio: ["pipe", "pipe", "pipe"],
		...options,
	}).trim();
}

/**
 * Merges upstream into a detached worktree at `work` (created from `repo`). Returns
 * { changed, sha, baseSha, upstreamSha, previous }; on conflict, aborts and throws with the paths.
 */
export function prepareMerge(repo, work, { upstreamUrl = UPSTREAM_URL, remote = "origin" } = {}) {
	const git = (cwd, ...args) => run("git", ["-c", "core.hooksPath=/dev/null", ...args], { cwd });
	git(repo, "fetch", "--no-tags", remote, `+refs/heads/${BASE}:refs/remotes/${remote}/${BASE}`);
	git(repo, "fetch", "--no-tags", upstreamUrl, `+refs/heads/${UPSTREAM.branch}:${UPSTREAM_REF}`);
	const previous = git(repo, "ls-remote", "--heads", remote, `refs/heads/${HEAD}`) !== "";
	if (previous) git(repo, "fetch", "--no-tags", remote, `+refs/heads/${HEAD}:refs/remotes/${remote}/${HEAD}`);
	const baseSha = checkedSha(git(repo, "rev-parse", `refs/remotes/${remote}/${BASE}`));
	const upstreamSha = checkedSha(git(repo, "rev-parse", UPSTREAM_REF));
	git(repo, "worktree", "add", "--detach", work, previous ? `refs/remotes/${remote}/${HEAD}` : baseSha);
	const upToDate = git(repo, "rev-list", "--count", `${baseSha}..${upstreamSha}`) === "0";
	if (upToDate) return { changed: false, sha: baseSha, baseSha, upstreamSha, previous };

	git(work, "config", "user.name", "robotutor-upstream[bot]");
	git(work, "config", "user.email", "robotutor-upstream@users.noreply.github.com");
	try {
		// Preserve both histories: bring the proposal up to the base, then merge upstream.
		git(work, "merge", "--no-edit", baseSha);
		git(work, "merge", "--no-edit", "--no-ff", "-m", `build: merge upstream ${UPSTREAM.repository}@${upstreamSha.slice(0, 12)}`, upstreamSha);
	} catch (error) {
		const conflicts = git(work, "diff", "--name-only", "--diff-filter=U");
		git(work, "merge", "--abort");
		throw new Error(`Upstream merge stopped; nothing pushed. Conflicts:\n${conflicts || error.message}`, {
			cause: error,
		});
	}
	writeFileSync(
		join(work, "robotutor", "upstream.json"),
		JSON.stringify({ ...UPSTREAM, sha: upstreamSha }, null, "\t") + "\n",
	);
	git(work, "add", "robotutor/upstream.json");
	if (git(work, "diff", "--cached", "--name-only")) {
		git(work, "commit", "-m", `build: record upstream ${upstreamSha.slice(0, 12)}`);
	}
	return { changed: true, sha: checkedSha(git(work, "rev-parse", "HEAD")), baseSha, upstreamSha, previous };
}

function proposalBody(result, check) {
	return [
		`Merges upstream ${UPSTREAM.repository}@${result.upstreamSha} into \`${BASE}\` (candidate ${result.sha}).`,
		"",
		"Both histories are preserved; the Robotutor patches are in `ROBOTUTOR.md`.",
		check === null
			? "**Contract not run.** Run `robotutor/check.sh` on this branch before merging."
			: check.ok
				? `**Contract passed** on ${result.sha.slice(0, 12)} (\`robotutor/check.sh\`: bundle build + ${check.summary}).`
				: `**Contract FAILED** on ${result.sha.slice(0, 12)}: ${check.summary}. Do not merge until it passes.`,
		"",
		"Merging this does not change OLMS: publish a release from the merged commit and bump OLMS's pin to adopt it.",
		"",
		"🤖 Generated by `robotutor/sync.mjs`",
	].join("\n");
}

function runCheck(work) {
	const result = spawnSync("bash", ["robotutor/check.sh"], { cwd: work, encoding: "utf8", maxBuffer: 256 * 1024 * 1024 });
	const output = `${result.stdout}\n${result.stderr}`;
	process.stdout.write(output.slice(-4000));
	const counts = output.match(/\d+ (?:passed|failed|flaky|skipped)/g) ?? [];
	return { ok: result.status === 0, summary: counts.length ? counts.join(", ") : `exit ${result.status}` };
}

export function main(args = process.argv.slice(2)) {
	if (args.some((arg) => !["--push", "--check", "--keep"].includes(arg))) {
		throw new Error("Usage: node robotutor/sync.mjs [--check] [--push] [--keep]");
	}
	const repo = run("git", ["rev-parse", "--show-toplevel"]);
	const work = mkdtempSync(join(tmpdir(), "geogebra-sync-"));
	rmSync(work, { recursive: true });
	let keep = args.includes("--keep");
	try {
		const result = prepareMerge(repo, work);
		console.log(
			result.changed
				? `Merged upstream ${result.upstreamSha.slice(0, 12)} into ${BASE}: candidate ${result.sha}.`
				: `${BASE} already contains upstream ${result.upstreamSha.slice(0, 12)}; nothing to propose.`,
		);
		if (!result.changed) return;
		const check = args.includes("--check") ? runCheck(work) : null;
		if (!args.includes("--push")) {
			keep = true;
			console.log(`Dry run: the candidate is in ${work}. Re-run with --push to propose it.`);
			return;
		}
		run("git", ["-c", "core.hooksPath=/dev/null", "push", "origin", `HEAD:refs/heads/${HEAD}`], { cwd: work });
		const open = run("gh", ["pr", "list", "-R", REPOSITORY, "--head", HEAD, "--base", BASE, "--json", "number", "--jq", ".[0].number"]);
		const title = `build: merge upstream GeoGebra ${result.upstreamSha.slice(0, 12)} (OLM-2025)`;
		const body = proposalBody(result, check);
		const url = open
			? (run("gh", ["pr", "edit", open, "-R", REPOSITORY, "--title", title, "--body", body]), `https://github.com/${REPOSITORY}/pull/${open}`)
			: run("gh", ["pr", "create", "-R", REPOSITORY, "--base", BASE, "--head", HEAD, "--title", title, "--body", body]);
		console.log(`Proposal: ${url}`);
		if (check && !check.ok) process.exitCode = 1;
	} finally {
		if (!keep) {
			run("git", ["worktree", "remove", "--force", work], { cwd: repo });
		}
	}
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	try {
		main();
	} catch (error) {
		console.error(error.message);
		process.exitCode = 1;
	}
}
